# Generated by Django 3.1.8 on 2021-07-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='originalComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_app.comment'),
        ),
    ]
