# Generated by Django 3.1.8 on 2021-07-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0002_comment_originalcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='originalComment',
            new_name='original_comment',
        ),
    ]
